# Generated by Django 5.1.5 on 2025-01-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_sensor_description_alter_sensor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='time_update',
        ),
    ]
