# Generated by Django 5.1.5 on 2025-01-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_alter_measurement_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
